server:
  port: 10010 #网关端口
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:80  #nacos 注册地址
    gateway: #网关
      routes: #路由
        - id: user-service  #路由id  只要唯一就可以
          uri: lb://userservice #路由的目标地址  lb 就是loadBalance负载均衡
          predicates: #断言   只有符合断言的请求才能通过网关
            - Path=/user/**  #路径断言

        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
